import { Injectable, Logger } from '@nestjs/common';
import { InjectDataSource, InjectRepository } from '@nestjs/typeorm';
import { DataSource, Repository } from 'typeorm';
import { HandlingUnitOrmEntity } from '../modules/wms/handling-unit/persistence/handling-unit.orm-entity';
import { InventoryBalanceOrmEntity } from '../modules/wms/inventory-balance/persistence/inventory-balance.orm-entity';
import { LocationOrmEntity } from '../modules/wms/location/persistence/location.orm-entity';
import { PickLineOrmEntity } from '../modules/wms/pick-line/persistence/pick-line.orm-entity';
import { PickOrderOrmEntity } from '../modules/wms/pick-order/persistence/pick-order.orm-entity';
import { ProductOrmEntity } from '../modules/wms/products/persistence/product.orm-entity';
import {
  HandlingUnitStatus,
  HandlingUnitType,
  PickLineStatus,
  PickOrderStatus,
  TransferLineStatus,
  TransferOrderStatus,
  ZoneType,
} from '../modules/wms/shared/domain/wms.enums';
import { TransferLineOrmEntity } from '../modules/wms/transfer-line/persistence/transfer-line.orm-entity';
import { TransferOrderOrmEntity } from '../modules/wms/transfer-order/persistence/transfer-order.orm-entity';
import { WarehouseOrmEntity } from '../modules/wms/warehouse/persistence/warehouse.orm-entity';
import { WmsUserOrmEntity } from '../modules/wms/wms-user/persistence/wms-user.orm-entity';
import { ZoneOrmEntity } from '../modules/wms/zone/persistence/zone.orm-entity';

/** UUIDs fixos para rastrear relações em demos e testes. */
const S = {
  uAlice: 'a1000000-0000-4000-8000-000000000001',
  uBob: 'a1000000-0000-4000-8000-000000000002',
  uCarol: 'a1000000-0000-4000-8000-000000000003',
  uDaniela: 'a1000000-0000-4000-8000-000000000004',
  uEduardo: 'a1000000-0000-4000-8000-000000000005',
  uFernanda: 'a1000000-0000-4000-8000-000000000006',
  whMain: 'b1000000-0000-4000-8000-000000000001',
  whSouth: 'b1000000-0000-4000-8000-000000000002',
  whNorth: 'b1000000-0000-4000-8000-000000000003',
  whMetro: 'b1000000-0000-4000-8000-000000000004',
  zStorage: 'c1000000-0000-4000-8000-000000000001',
  zPicking: 'c1000000-0000-4000-8000-000000000002',
  zShipping: 'c1000000-0000-4000-8000-000000000003',
  zMainRecv: 'c1000000-0000-4000-8000-000000000006',
  zMainStg: 'c1000000-0000-4000-8000-000000000007',
  zStorageB: 'c1000000-0000-4000-8000-000000000008',
  zSouthStorage: 'c1000000-0000-4000-8000-000000000004',
  zSouthRecv: 'c1000000-0000-4000-8000-000000000005',
  zSouthShip: 'c1000000-0000-4000-8000-000000000009',
  zSouthPick: 'c1000000-0000-4000-8000-00000000000a',
  locBulkA: 'd1000000-0000-4000-8000-000000000001',
  locBulkB: 'd1000000-0000-4000-8000-000000000002',
  locPick1: 'd1000000-0000-4000-8000-000000000003',
  locPick2: 'd1000000-0000-4000-8000-000000000004',
  locDock: 'd1000000-0000-4000-8000-000000000005',
  locSouthBulk: 'd1000000-0000-4000-8000-000000000006',
  locRecv01: 'd1000000-0000-4000-8000-000000000007',
  locStg01: 'd1000000-0000-4000-8000-000000000008',
  locBulkC: 'd1000000-0000-4000-8000-000000000009',
  locSouthDock: 'd1000000-0000-4000-8000-00000000000a',
  locSouthPF: 'd1000000-0000-4000-8000-00000000000b',
  locNorth1: 'd1000000-0000-4000-8000-00000000000c',
  locMetro1: 'd1000000-0000-4000-8000-00000000000d',
  pSkuA: 'e1000000-0000-4000-8000-000000000001',
  pSkuB: 'e1000000-0000-4000-8000-000000000002',
  pSkuC: 'e1000000-0000-4000-8000-000000000003',
  pSkuD: 'e1000000-0000-4000-8000-000000000004',
  pSkuE: 'e1000000-0000-4000-8000-000000000005',
  pSkuF: 'e1000000-0000-4000-8000-000000000006',
  pSkuG: 'e1000000-0000-4000-8000-000000000007',
  pSkuH: 'e1000000-0000-4000-8000-000000000008',
  huPallet: 'f1000000-0000-4000-8000-000000000001',
  huTote: 'f1000000-0000-4000-8000-000000000002',
  huBlocked: 'f1000000-0000-4000-8000-000000000003',
  huPallet2: 'f1000000-0000-4000-8000-000000000004',
  huTote2: 'f1000000-0000-4000-8000-000000000005',
  huCase2: 'f1000000-0000-4000-8000-000000000006',
  poDraft: '10100000-0000-4000-8000-000000000001',
  poReleased: '10100000-0000-4000-8000-000000000002',
  poPicking: '10100000-0000-4000-8000-000000000003',
  poPicked: '10100000-0000-4000-8000-000000000004',
  poCancelled: '10100000-0000-4000-8000-000000000005',
  poDraftSul: '10100000-0000-4000-8000-000000000006',
  poReleasedSul: '10100000-0000-4000-8000-000000000007',
  poPickingSul: '10100000-0000-4000-8000-000000000008',
  poPickedSul: '10100000-0000-4000-8000-000000000009',
  poCancelled2: '10100000-0000-4000-8000-00000000000a',
  toDraft: '20100000-0000-4000-8000-000000000001',
  toProgress: '20100000-0000-4000-8000-000000000002',
  toDone: '20100000-0000-4000-8000-000000000003',
  toDraftSul: '20100000-0000-4000-8000-000000000004',
  toProgress2: '20100000-0000-4000-8000-000000000005',
  toDoneSul: '20100000-0000-4000-8000-000000000006',
  zNorthStor: 'c1000000-0000-4000-8000-00000000000b',
  zMetroPick: 'c1000000-0000-4000-8000-00000000000c',
} as const;

@Injectable()
export class DatabaseSeedService {
  private readonly logger = new Logger(DatabaseSeedService.name);

  constructor(
    @InjectDataSource()
    private readonly dataSource: DataSource,
    @InjectRepository(ProductOrmEntity)
    private readonly products: Repository<ProductOrmEntity>,
    @InjectRepository(WmsUserOrmEntity)
    private readonly wmsUsers: Repository<WmsUserOrmEntity>,
    @InjectRepository(WarehouseOrmEntity)
    private readonly warehouses: Repository<WarehouseOrmEntity>,
    @InjectRepository(ZoneOrmEntity)
    private readonly zones: Repository<ZoneOrmEntity>,
    @InjectRepository(LocationOrmEntity)
    private readonly locations: Repository<LocationOrmEntity>,
    @InjectRepository(HandlingUnitOrmEntity)
    private readonly handlingUnits: Repository<HandlingUnitOrmEntity>,
    @InjectRepository(InventoryBalanceOrmEntity)
    private readonly inventoryBalances: Repository<InventoryBalanceOrmEntity>,
    @InjectRepository(PickOrderOrmEntity)
    private readonly pickOrders: Repository<PickOrderOrmEntity>,
    @InjectRepository(PickLineOrmEntity)
    private readonly pickLines: Repository<PickLineOrmEntity>,
    @InjectRepository(TransferOrderOrmEntity)
    private readonly transferOrders: Repository<TransferOrderOrmEntity>,
    @InjectRepository(TransferLineOrmEntity)
    private readonly transferLines: Repository<TransferLineOrmEntity>,
  ) {}

  async run(): Promise<void> {
    this.logger.log('Limpando tabelas WMS + produtos…');
    await this.clearAll();
    this.logger.log('Inserindo dados de seed…');
    await this.insertSeed();
    this.logger.log('Seed concluído.');
  }

  /**
   * PostgreSQL: TRUNCATE … CASCADE em lote respeita FKs.
   */
  private async clearAll(): Promise<void> {
    await this.dataSource.query(`
      TRUNCATE TABLE
        "transfer_lines",
        "pick_lines",
        "inventory_balances",
        "transfer_orders",
        "pick_orders",
        "handling_units",
        "locations",
        "zones",
        "products",
        "wms_users",
        "warehouses"
      RESTART IDENTITY CASCADE;
    `);
  }

  private async insertSeed(): Promise<void> {
    await this.wmsUsers.save([
      {
        id: S.uAlice,
        code: 'U-ALICE',
        displayName: 'Alice (planejamento)',
        active: true,
      },
      {
        id: S.uBob,
        code: 'U-BOB',
        displayName: 'Bob (separador)',
        active: true,
      },
      {
        id: S.uCarol,
        code: 'U-CAROL',
        displayName: 'Carol (expedição)',
        active: true,
      },
      {
        id: S.uDaniela,
        code: 'U-DANIELA',
        displayName: 'Daniela (recebimento)',
        active: true,
      },
      {
        id: S.uEduardo,
        code: 'U-EDUARDO',
        displayName: 'Eduardo (inventário)',
        active: true,
      },
      {
        id: S.uFernanda,
        code: 'U-FERNANDA',
        displayName: 'Fernanda (coordenação)',
        active: true,
      },
    ]);
    await this.warehouses.save([
      {
        id: S.whMain,
        code: 'WH01',
        name: 'CD Central — São Paulo',
        active: true,
      },
      {
        id: S.whSouth,
        code: 'WH02',
        name: 'CD Sul — Curitiba',
        active: true,
      },
      {
        id: S.whNorth,
        code: 'WH03',
        name: 'CD Nordeste — Recife',
        active: true,
      },
      {
        id: S.whMetro,
        code: 'WH04',
        name: 'Cross-docking — Belo Horizonte',
        active: true,
      },
    ]);
    await this.zones.save([
      {
        id: S.zStorage,
        warehouseId: S.whMain,
        code: 'STOR-A',
        name: 'Armazenagem bloco A',
        zoneType: ZoneType.STORAGE,
      },
      {
        id: S.zPicking,
        warehouseId: S.whMain,
        code: 'PICK-F',
        name: 'Separação frente de loja',
        zoneType: ZoneType.PICKING,
      },
      {
        id: S.zShipping,
        warehouseId: S.whMain,
        code: 'SHIP-1',
        name: 'Doca de expedição 1',
        zoneType: ZoneType.SHIPPING,
      },
      {
        id: S.zMainRecv,
        warehouseId: S.whMain,
        code: 'RCV-01',
        name: 'Recebimento principal',
        zoneType: ZoneType.RECEIVING,
      },
      {
        id: S.zMainStg,
        warehouseId: S.whMain,
        code: 'STG-01',
        name: 'Área de consolidação',
        zoneType: ZoneType.STAGING,
      },
      {
        id: S.zStorageB,
        warehouseId: S.whMain,
        code: 'STOR-B',
        name: 'Armazenagem bloco B',
        zoneType: ZoneType.STORAGE,
      },
      {
        id: S.zSouthStorage,
        warehouseId: S.whSouth,
        code: 'STOR-S',
        name: 'Armazenagem Sul',
        zoneType: ZoneType.STORAGE,
      },
      {
        id: S.zSouthRecv,
        warehouseId: S.whSouth,
        code: 'RCV-S',
        name: 'Recebimento Sul',
        zoneType: ZoneType.RECEIVING,
      },
      {
        id: S.zSouthShip,
        warehouseId: S.whSouth,
        code: 'SHIP-S',
        name: 'Expedição Sul',
        zoneType: ZoneType.SHIPPING,
      },
      {
        id: S.zSouthPick,
        warehouseId: S.whSouth,
        code: 'PICK-S',
        name: 'Separação Sul',
        zoneType: ZoneType.PICKING,
      },
      {
        id: S.zNorthStor,
        warehouseId: S.whNorth,
        code: 'STOR-N',
        name: 'Armazenagem Nordeste',
        zoneType: ZoneType.STORAGE,
      },
      {
        id: S.zMetroPick,
        warehouseId: S.whMetro,
        code: 'PICK-M',
        name: 'Separação expressa BH',
        zoneType: ZoneType.PICKING,
      },
    ]);
    await this.locations.save([
      {
        id: S.locBulkA,
        zoneId: S.zStorage,
        code: 'A-01-01',
        aisle: 'A',
        bay: '01',
        level: '01',
        active: true,
      },
      {
        id: S.locBulkB,
        zoneId: S.zStorage,
        code: 'A-01-02',
        aisle: 'A',
        bay: '01',
        level: '02',
        active: true,
      },
      {
        id: S.locPick1,
        zoneId: S.zPicking,
        code: 'PF-01',
        aisle: 'PF',
        bay: '01',
        level: '1',
        active: true,
      },
      {
        id: S.locPick2,
        zoneId: S.zPicking,
        code: 'PF-02',
        aisle: 'PF',
        bay: '02',
        level: '1',
        active: true,
      },
      {
        id: S.locDock,
        zoneId: S.zShipping,
        code: 'DOCK-01',
        aisle: 'D',
        bay: '01',
        level: null,
        active: true,
      },
      {
        id: S.locSouthBulk,
        zoneId: S.zSouthStorage,
        code: 'S-01-01',
        aisle: 'S',
        bay: '01',
        level: '01',
        active: true,
      },
      {
        id: S.locRecv01,
        zoneId: S.zMainRecv,
        code: 'RCV-D1',
        aisle: 'R',
        bay: '01',
        level: null,
        active: true,
      },
      {
        id: S.locStg01,
        zoneId: S.zMainStg,
        code: 'STG-01',
        aisle: 'G',
        bay: '01',
        level: '1',
        active: true,
      },
      {
        id: S.locBulkC,
        zoneId: S.zStorageB,
        code: 'B-02-01',
        aisle: 'B',
        bay: '02',
        level: '01',
        active: true,
      },
      {
        id: S.locSouthDock,
        zoneId: S.zSouthShip,
        code: 'DOCK-S1',
        aisle: 'DS',
        bay: '01',
        level: null,
        active: true,
      },
      {
        id: S.locSouthPF,
        zoneId: S.zSouthPick,
        code: 'PFS-01',
        aisle: 'PS',
        bay: '01',
        level: '1',
        active: true,
      },
      {
        id: S.locNorth1,
        zoneId: S.zNorthStor,
        code: 'N-01-01',
        aisle: 'N',
        bay: '01',
        level: '01',
        active: true,
      },
      {
        id: S.locMetro1,
        zoneId: S.zMetroPick,
        code: 'M-EXP-01',
        aisle: 'M',
        bay: '01',
        level: '1',
        active: true,
      },
    ]);
    await this.products.save([
      {
        id: S.pSkuA,
        name: 'Caixa de parafusos M6 zincado',
        barcode: 'SEED-SKU-A',
        description: 'Fixação em massa; paletizado no CD Central.',
      },
      {
        id: S.pSkuB,
        name: 'Fita adesiva transparente 48 mm x 50 m',
        barcode: 'SEED-SKU-B',
        description: 'Embalagem e fechamento de caixas.',
      },
      {
        id: S.pSkuC,
        name: 'Etiquetas térmicas 100 x 150 mm',
        barcode: 'SEED-SKU-C',
        description: 'Bobina para impressora de etiquetas de transporte.',
      },
      {
        id: S.pSkuD,
        name: 'Tubo PVC soldável 50 mm',
        barcode: 'SEED-SKU-D',
        description: 'Produto volumoso; manuseio com empilhadeira.',
      },
      {
        id: S.pSkuE,
        name: 'Luva de proteção nitrílica tamanho G',
        barcode: 'SEED-SKU-E',
        description: 'EPI descartável; lote homologado NR-6.',
      },
      {
        id: S.pSkuF,
        name: 'Caixa de papelão ondulado 40 x 30 x 25 cm',
        barcode: 'SEED-SKU-F',
        description: 'Embalagem secundária para e-commerce.',
      },
      {
        id: S.pSkuG,
        name: 'Spray lubrificante multiuso 300 ml',
        barcode: 'SEED-SKU-G',
        description: 'Manutenção leve; armazenar longe de calor.',
      },
      {
        id: S.pSkuH,
        name: 'Cinta de poliéster para amarração 50 mm',
        barcode: 'SEED-SKU-H',
        description: 'Unitização de paletes na doca.',
      },
    ]);
    await this.handlingUnits.save([
      {
        id: S.huPallet,
        code: 'SSCC-SEED-PALLET-01',
        type: HandlingUnitType.PALLET,
        currentLocationId: S.locBulkA,
        status: HandlingUnitStatus.IN_USE,
      },
      {
        id: S.huTote,
        code: 'TOTE-SEED-VAZIO-01',
        type: HandlingUnitType.TOTE,
        currentLocationId: S.locPick1,
        status: HandlingUnitStatus.EMPTY,
      },
      {
        id: S.huBlocked,
        code: 'CX-SEED-BLOQUEADA-01',
        type: HandlingUnitType.CASE,
        currentLocationId: S.locBulkB,
        status: HandlingUnitStatus.BLOCKED,
      },
      {
        id: S.huPallet2,
        code: 'SSCC-SEED-PALLET-02',
        type: HandlingUnitType.PALLET,
        currentLocationId: S.locBulkC,
        status: HandlingUnitStatus.IN_USE,
      },
      {
        id: S.huTote2,
        code: 'TOTE-SEED-EM-USO-02',
        type: HandlingUnitType.TOTE,
        currentLocationId: S.locSouthPF,
        status: HandlingUnitStatus.IN_USE,
      },
      {
        id: S.huCase2,
        code: 'CX-SEED-REC-01',
        type: HandlingUnitType.CASE,
        currentLocationId: S.locRecv01,
        status: HandlingUnitStatus.IN_USE,
      },
    ]);
    await this.inventoryBalances.save([
      {
        productId: S.pSkuA,
        locationId: S.locBulkA,
        handlingUnitId: S.huPallet,
        quantityOnHand: 240,
        quantityReserved: 40,
      },
      {
        productId: S.pSkuB,
        locationId: S.locPick1,
        handlingUnitId: null,
        quantityOnHand: 80,
        quantityReserved: 0,
      },
      {
        productId: S.pSkuC,
        locationId: S.locPick2,
        handlingUnitId: null,
        quantityOnHand: 25,
        quantityReserved: 10,
      },
      {
        productId: S.pSkuD,
        locationId: S.locBulkB,
        handlingUnitId: null,
        quantityOnHand: 12,
        quantityReserved: 0,
      },
      {
        productId: S.pSkuB,
        locationId: S.locSouthBulk,
        handlingUnitId: null,
        quantityOnHand: 30,
        quantityReserved: 0,
      },
      {
        productId: S.pSkuE,
        locationId: S.locSouthBulk,
        handlingUnitId: null,
        quantityOnHand: 200,
        quantityReserved: 24,
      },
      {
        productId: S.pSkuE,
        locationId: S.locBulkC,
        handlingUnitId: S.huPallet2,
        quantityOnHand: 500,
        quantityReserved: 50,
      },
      {
        productId: S.pSkuF,
        locationId: S.locStg01,
        handlingUnitId: null,
        quantityOnHand: 120,
        quantityReserved: 0,
      },
      {
        productId: S.pSkuG,
        locationId: S.locRecv01,
        handlingUnitId: S.huCase2,
        quantityOnHand: 48,
        quantityReserved: 0,
      },
      {
        productId: S.pSkuH,
        locationId: S.locDock,
        handlingUnitId: null,
        quantityOnHand: 200,
        quantityReserved: 20,
      },
      {
        productId: S.pSkuC,
        locationId: S.locNorth1,
        handlingUnitId: null,
        quantityOnHand: 60,
        quantityReserved: 0,
      },
      {
        productId: S.pSkuA,
        locationId: S.locMetro1,
        handlingUnitId: null,
        quantityOnHand: 15,
        quantityReserved: 5,
      },
      {
        productId: S.pSkuD,
        locationId: S.locSouthPF,
        handlingUnitId: S.huTote2,
        quantityOnHand: 8,
        quantityReserved: 0,
      },
    ]);
    const now = new Date();
    await this.pickOrders.save([
      {
        id: S.poDraft,
        orderNumber: 'PO-SEED-RASCUNHO',
        warehouseId: S.whMain,
        status: PickOrderStatus.DRAFT,
        priority: 5,
        createdByUserId: S.uAlice,
        releasedByUserId: null,
        releasedAt: null,
        completedByUserId: null,
        completedAt: null,
      },
      {
        id: S.poReleased,
        orderNumber: 'PO-SEED-LIBERADO',
        warehouseId: S.whMain,
        status: PickOrderStatus.RELEASED,
        priority: 3,
        createdByUserId: S.uAlice,
        releasedByUserId: S.uAlice,
        releasedAt: now,
        completedByUserId: null,
        completedAt: null,
      },
      {
        id: S.poPicking,
        orderNumber: 'PO-SEED-SEPARANDO',
        warehouseId: S.whMain,
        status: PickOrderStatus.PICKING,
        priority: 2,
        createdByUserId: S.uAlice,
        releasedByUserId: S.uAlice,
        releasedAt: now,
        completedByUserId: null,
        completedAt: null,
      },
      {
        id: S.poPicked,
        orderNumber: 'PO-SEED-CONCLUIDO',
        warehouseId: S.whMain,
        status: PickOrderStatus.PICKED,
        priority: 1,
        createdByUserId: S.uAlice,
        releasedByUserId: S.uAlice,
        releasedAt: now,
        completedByUserId: S.uBob,
        completedAt: now,
      },
      {
        id: S.poCancelled,
        orderNumber: 'PO-SEED-CANCELADO',
        warehouseId: S.whMain,
        status: PickOrderStatus.CANCELLED,
        priority: 9,
        createdByUserId: S.uAlice,
        releasedByUserId: null,
        releasedAt: null,
        completedByUserId: null,
        completedAt: null,
      },
      {
        id: S.poDraftSul,
        orderNumber: 'PO-SEED-SUL-RASCUNHO',
        warehouseId: S.whSouth,
        status: PickOrderStatus.DRAFT,
        priority: 6,
        createdByUserId: S.uFernanda,
        releasedByUserId: null,
        releasedAt: null,
        completedByUserId: null,
        completedAt: null,
      },
      {
        id: S.poReleasedSul,
        orderNumber: 'PO-SEED-SUL-LIBERADO',
        warehouseId: S.whSouth,
        status: PickOrderStatus.RELEASED,
        priority: 4,
        createdByUserId: S.uFernanda,
        releasedByUserId: S.uFernanda,
        releasedAt: now,
        completedByUserId: null,
        completedAt: null,
      },
      {
        id: S.poPickingSul,
        orderNumber: 'PO-SEED-SUL-SEPARANDO',
        warehouseId: S.whSouth,
        status: PickOrderStatus.PICKING,
        priority: 3,
        createdByUserId: S.uFernanda,
        releasedByUserId: S.uFernanda,
        releasedAt: now,
        completedByUserId: null,
        completedAt: null,
      },
      {
        id: S.poPickedSul,
        orderNumber: 'PO-SEED-SUL-CONCLUIDO',
        warehouseId: S.whSouth,
        status: PickOrderStatus.PICKED,
        priority: 2,
        createdByUserId: S.uFernanda,
        releasedByUserId: S.uFernanda,
        releasedAt: now,
        completedByUserId: S.uBob,
        completedAt: now,
      },
      {
        id: S.poCancelled2,
        orderNumber: 'PO-SEED-CANCELADO-2',
        warehouseId: S.whMetro,
        status: PickOrderStatus.CANCELLED,
        priority: 8,
        createdByUserId: S.uDaniela,
        releasedByUserId: null,
        releasedAt: null,
        completedByUserId: null,
        completedAt: null,
      },
    ]);
    await this.pickLines.save([
      {
        pickOrderId: S.poDraft,
        productId: S.pSkuA,
        quantityOrdered: 10,
        quantityPicked: 0,
        sourceLocationId: S.locBulkA,
        status: PickLineStatus.OPEN,
        pickedByUserId: null,
        pickedAt: null,
      },
      {
        pickOrderId: S.poReleased,
        productId: S.pSkuB,
        quantityOrdered: 15,
        quantityPicked: 0,
        sourceLocationId: S.locPick1,
        status: PickLineStatus.OPEN,
        pickedByUserId: null,
        pickedAt: null,
      },
      {
        pickOrderId: S.poReleased,
        productId: S.pSkuC,
        quantityOrdered: 5,
        quantityPicked: 0,
        sourceLocationId: S.locPick2,
        status: PickLineStatus.OPEN,
        pickedByUserId: null,
        pickedAt: null,
      },
      {
        pickOrderId: S.poPicking,
        productId: S.pSkuB,
        quantityOrdered: 20,
        quantityPicked: 8,
        sourceLocationId: S.locPick1,
        status: PickLineStatus.PARTIAL,
        pickedByUserId: S.uBob,
        pickedAt: now,
      },
      {
        pickOrderId: S.poPicking,
        productId: S.pSkuC,
        quantityOrdered: 10,
        quantityPicked: 0,
        sourceLocationId: S.locPick2,
        status: PickLineStatus.OPEN,
        pickedByUserId: null,
        pickedAt: null,
      },
      {
        pickOrderId: S.poPicked,
        productId: S.pSkuD,
        quantityOrdered: 4,
        quantityPicked: 4,
        sourceLocationId: S.locBulkB,
        status: PickLineStatus.DONE,
        pickedByUserId: S.uBob,
        pickedAt: now,
      },
      {
        pickOrderId: S.poCancelled,
        productId: S.pSkuA,
        quantityOrdered: 99,
        quantityPicked: 0,
        sourceLocationId: null,
        status: PickLineStatus.OPEN,
        pickedByUserId: null,
        pickedAt: null,
      },
      {
        pickOrderId: S.poDraftSul,
        productId: S.pSkuB,
        quantityOrdered: 12,
        quantityPicked: 0,
        sourceLocationId: S.locSouthBulk,
        status: PickLineStatus.OPEN,
        pickedByUserId: null,
        pickedAt: null,
      },
      {
        pickOrderId: S.poReleasedSul,
        productId: S.pSkuD,
        quantityOrdered: 6,
        quantityPicked: 0,
        sourceLocationId: S.locSouthPF,
        status: PickLineStatus.OPEN,
        pickedByUserId: null,
        pickedAt: null,
      },
      {
        pickOrderId: S.poReleasedSul,
        productId: S.pSkuE,
        quantityOrdered: 24,
        quantityPicked: 0,
        sourceLocationId: S.locSouthBulk,
        status: PickLineStatus.OPEN,
        pickedByUserId: null,
        pickedAt: null,
      },
      {
        pickOrderId: S.poPickingSul,
        productId: S.pSkuB,
        quantityOrdered: 18,
        quantityPicked: 10,
        sourceLocationId: S.locSouthBulk,
        status: PickLineStatus.PARTIAL,
        pickedByUserId: S.uBob,
        pickedAt: now,
      },
      {
        pickOrderId: S.poPickingSul,
        productId: S.pSkuH,
        quantityOrdered: 4,
        quantityPicked: 0,
        sourceLocationId: S.locSouthDock,
        status: PickLineStatus.OPEN,
        pickedByUserId: null,
        pickedAt: null,
      },
      {
        pickOrderId: S.poPickedSul,
        productId: S.pSkuC,
        quantityOrdered: 8,
        quantityPicked: 8,
        sourceLocationId: S.locSouthPF,
        status: PickLineStatus.DONE,
        pickedByUserId: S.uCarol,
        pickedAt: now,
      },
      {
        pickOrderId: S.poCancelled2,
        productId: S.pSkuA,
        quantityOrdered: 50,
        quantityPicked: 0,
        sourceLocationId: S.locMetro1,
        status: PickLineStatus.OPEN,
        pickedByUserId: null,
        pickedAt: null,
      },
    ]);
    await this.transferOrders.save([
      {
        id: S.toDraft,
        referenceCode: 'TRF-SEED-RASCUNHO',
        warehouseId: S.whMain,
        status: TransferOrderStatus.DRAFT,
        createdByUserId: S.uAlice,
        completedByUserId: null,
        completedAt: null,
      },
      {
        id: S.toProgress,
        referenceCode: 'TRF-SEED-EM-ANDAMENTO',
        warehouseId: S.whMain,
        status: TransferOrderStatus.IN_PROGRESS,
        createdByUserId: S.uAlice,
        completedByUserId: null,
        completedAt: null,
      },
      {
        id: S.toDone,
        referenceCode: 'TRF-SEED-CONCLUIDO',
        warehouseId: S.whMain,
        status: TransferOrderStatus.COMPLETED,
        createdByUserId: S.uAlice,
        completedByUserId: S.uCarol,
        completedAt: now,
      },
      {
        id: S.toDraftSul,
        referenceCode: 'TRF-SEED-SUL-RASCUNHO',
        warehouseId: S.whSouth,
        status: TransferOrderStatus.DRAFT,
        createdByUserId: S.uFernanda,
        completedByUserId: null,
        completedAt: null,
      },
      {
        id: S.toProgress2,
        referenceCode: 'TRF-SEED-SUL-ANDAMENTO',
        warehouseId: S.whSouth,
        status: TransferOrderStatus.IN_PROGRESS,
        createdByUserId: S.uDaniela,
        completedByUserId: null,
        completedAt: null,
      },
      {
        id: S.toDoneSul,
        referenceCode: 'TRF-SEED-SUL-CONCLUIDO',
        warehouseId: S.whSouth,
        status: TransferOrderStatus.COMPLETED,
        createdByUserId: S.uEduardo,
        completedByUserId: S.uCarol,
        completedAt: now,
      },
    ]);
    await this.transferLines.save([
      {
        transferOrderId: S.toDraft,
        productId: S.pSkuA,
        quantity: 12,
        fromLocationId: S.locBulkA,
        toLocationId: S.locPick1,
        fromHandlingUnitId: S.huPallet,
        toHandlingUnitId: null,
        status: TransferLineStatus.OPEN,
      },
      {
        transferOrderId: S.toProgress,
        productId: S.pSkuB,
        quantity: 6,
        fromLocationId: S.locPick1,
        toLocationId: S.locDock,
        fromHandlingUnitId: null,
        toHandlingUnitId: S.huTote,
        status: TransferLineStatus.DONE,
      },
      {
        transferOrderId: S.toProgress,
        productId: S.pSkuC,
        quantity: 3,
        fromLocationId: S.locPick2,
        toLocationId: S.locDock,
        fromHandlingUnitId: null,
        toHandlingUnitId: null,
        status: TransferLineStatus.OPEN,
      },
      {
        transferOrderId: S.toDone,
        productId: S.pSkuD,
        quantity: 2,
        fromLocationId: S.locBulkB,
        toLocationId: S.locDock,
        fromHandlingUnitId: null,
        toHandlingUnitId: null,
        status: TransferLineStatus.DONE,
      },
      {
        transferOrderId: S.toDraftSul,
        productId: S.pSkuB,
        quantity: 20,
        fromLocationId: S.locSouthBulk,
        toLocationId: S.locSouthPF,
        fromHandlingUnitId: null,
        toHandlingUnitId: null,
        status: TransferLineStatus.OPEN,
      },
      {
        transferOrderId: S.toDraftSul,
        productId: S.pSkuF,
        quantity: 30,
        fromLocationId: S.locStg01,
        toLocationId: S.locSouthBulk,
        fromHandlingUnitId: null,
        toHandlingUnitId: null,
        status: TransferLineStatus.OPEN,
      },
      {
        transferOrderId: S.toProgress2,
        productId: S.pSkuG,
        quantity: 12,
        fromLocationId: S.locRecv01,
        toLocationId: S.locSouthDock,
        fromHandlingUnitId: S.huCase2,
        toHandlingUnitId: null,
        status: TransferLineStatus.DONE,
      },
      {
        transferOrderId: S.toProgress2,
        productId: S.pSkuH,
        quantity: 15,
        fromLocationId: S.locDock,
        toLocationId: S.locStg01,
        fromHandlingUnitId: null,
        toHandlingUnitId: null,
        status: TransferLineStatus.OPEN,
      },
      {
        transferOrderId: S.toDoneSul,
        productId: S.pSkuE,
        quantity: 100,
        fromLocationId: S.locBulkC,
        toLocationId: S.locSouthBulk,
        fromHandlingUnitId: S.huPallet2,
        toHandlingUnitId: null,
        status: TransferLineStatus.DONE,
      },
      {
        transferOrderId: S.toDoneSul,
        productId: S.pSkuC,
        quantity: 10,
        fromLocationId: S.locNorth1,
        toLocationId: S.locMetro1,
        fromHandlingUnitId: null,
        toHandlingUnitId: null,
        status: TransferLineStatus.DONE,
      },
    ]);
  }
}
